### ISSUE TITLE
Cannot send alert due to timestamp exception

### ISSUE THREAD

**Issue by sdressler** [MikeSafonov/prometheus-telegram-alert#3]
On SHA1 ... I cannot send alerts from alertmanager version 0.16.2. An alert results in the following exception:

> 10:45:47.789 [http-nio-8080-exec-1] WARN  org.springframework.web.servlet.mvc.support.DefaultHandlerExceptionResolver - Resolved [org.springframework.http.converter.HttpMessageNotReadableException: JSON parse error: Cannot deseri
alize value of type `java.time.LocalDateTime` from String "2019-04-29T10:45:17.406189323+02:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2019-04-29T10:45:17.406189323+02:00'
could not be parsed, unparsed text found at index 29; nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize value of type `java.time.LocalDateTime` from String "2019-04-29T10:45:17.4061
89323+02:00": Failed to deserialize java.time.LocalDateTime: (java.time.format.DateTimeParseException) Text '2019-04-29T10:45:17.406189323+02:00' could not be parsed, unparsed text found at index 29
 at [Source: (PushbackInputStream); line: 1, column: 300] (through reference chain: com.github.mikesafonov.prometheus.telegram.dto.AlertManagerNotification["alerts"]->java.util.ArrayList[0]->com.github.mikesafonov.prometheus.tele
gram.dto.Alert["startsAt"])]

My `alertmanager.yml` looks like:

```
route:
  repeat_interval: 15m
  group_wait: 30s
  group_interval: 5m
  receiver: 'rocketchat'
  routes:
    - receiver: 'telegram'

receivers:
  - name: 'rocketchat'
    webhook_configs:
      - send_resolved: true
        url: 'https://my-chat-hook.com/alert'
  - name: 'telegram'
    webhook_configs:
      - send_resolved: true
        url: 'http://localhost:8080/alert'
```
